"""Create regional production table

Revision ID: 2d71c9020160
Revises:
Create Date: 2020-12-15 17:11:32.344492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d71c9020160"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regional_production",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_code", sa.String(), nullable=True),
        sa.Column("region_string", sa.String(), nullable=True),
        sa.Column("dataset_id", sa.String(), nullable=True),
        sa.Column("record_id", sa.String(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("total_consumption", sa.Float(), nullable=True),
        sa.Column("production", sa.JSON(), nullable=True),
        sa.Column("flux", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("regional_production")
    # ### end Alembic commands ###
